---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    commit-message:
      prefix: "build"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
    groups:
      runtime-dependencies:
        dependency-type: "production"
        patterns:
          - "*"
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
